---
- name: Install Docker via official repositories
  hosts: all
  become: yes

  tasks:
    - name: Determine package manager (APT or DNF)
      ansible.builtin.set_fact:
        pkg_manager: "{{ 'apt' if ansible_pkg_mgr == 'apt' else 'dnf' }}"

    - name: Install prerequisites (APT)
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: pkg_manager == 'apt'

    - name: Install prerequisites (DNF)
      ansible.builtin.dnf:
        name:
          - dnf-plugins-core
        state: present
      when: pkg_manager == 'dnf'

    - name: Add Docker GPG key (APT)
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present
      when: pkg_manager == 'apt'

    - name: Add Docker repository (APT)
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ {'x86_64': 'amd64', 'aarch64': 'arm64', 'armv7l': 'armhf', 'ppc64le': 'ppc64le'}[ansible_architecture] | default('amd64') }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        update_cache: yes
      when: pkg_manager == 'apt'

    - name: Add Docker repository (DNF)
      ansible.builtin.dnf_repository:
        name: docker-ce
        description: "Docker CE Stable"
        baseurl: "https://download.docker.com/linux/{{ 'centos' if ansible_distribution == 'CentOS' else ansible_distribution | lower }}/$releasever/$basearch/stable"
        gpgkey: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        gpgcheck: yes
        enabled: yes
      when: pkg_manager == 'dnf'

    - name: Install Docker packages
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user | default(ansible_ssh_user) | default(ansible_user_id) }}"
        groups: docker
        append: yes
      when: "ansible_user | default(ansible_ssh_user) | default(ansible_user_id) != 'root'"
      notify: Notify about docker group changes

  handlers:
    - name: Notify about docker group changes
      ansible.builtin.debug:
        msg: "User added to docker group. You need to logout and login again for changes to take effect."