---
- name: Migrate Docker installation to new keyring format
  hosts: all
  become: yes

  tasks:
    - name: Check if system uses APT
      ansible.builtin.set_fact:
        pkg_manager: "{{ 'apt' if ansible_pkg_mgr == 'apt' else 'dnf' }}"
  
    - name: Remove old Docker GPG key (APT)
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: absent
      when: pkg_manager == 'apt'

    - name: Remove old Docker repository file (APT)
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent
      when: pkg_manager == 'apt'
      ignore_errors: yes

    - name: Create keyring directory for Docker (APT)
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755
      when: pkg_manager == 'apt'

    - name: Add Docker GPG key to keyring (APT)
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        dest: /etc/apt/keyrings/docker.asc
        mode: 0644
      when: pkg_manager == 'apt'

    - name: Add Docker repository with new format (APT)
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ {'x86_64': 'amd64', 'aarch64': 'arm64', 'armv7l': 'armhf', 'ppc64le': 'ppc64le'}[ansible_architecture] | default('amd64') }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        update_cache: yes
      when: pkg_manager == 'apt'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: pkg_manager == 'apt'

    - name: Verify Docker installation
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false
      ignore_errors: yes

    - name: Show Docker version
      ansible.builtin.debug:
        var: docker_version.stdout
      when: docker_version is succeeded