---
- name: Install Visual Studio Code
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Verify supported distribution
      ansible.builtin.assert:
        that: ansible_facts['os_family'] in ['Debian', 'RedHat']
        msg: "Only Debian/Ubuntu and RHEL/CentOS/RockyLinux/AlmaLinux are supported"

    # Common prerequisites
    - name: Install curl (all systems)
      ansible.builtin.package:
        name: curl
        state: present

    # Debian/Ubuntu specific tasks
    - name: Install APT prerequisites
      ansible.builtin.package:
        name:
          - gpg
          - apt-transport-https
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Download Microsoft GPG key
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /tmp/microsoft.asc
        mode: '0644'
      when: ansible_facts['os_family'] == 'Debian'

    - name: Dearmor and install GPG key (Debian/Ubuntu)
      ansible.builtin.shell: |
        gpg --dearmor /tmp/microsoft.asc
        mv /tmp/microsoft.asc.gpg /usr/share/keyrings/microsoft.gpg
        chmod 644 /usr/share/keyrings/microsoft.gpg
      args:
        creates: /usr/share/keyrings/microsoft.gpg
      when: ansible_facts['os_family'] == 'Debian'

    - name: Clean up temporary key file
      ansible.builtin.file:
        path: /tmp/microsoft.asc
        state: absent
      when: ansible_facts['os_family'] == 'Debian'

    - name: Add VS Code repository (Debian/Ubuntu)
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"
        state: present
        filename: vscode
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'

    # RHEL/CentOS specific tasks
    - name: Import Microsoft GPG key (RPM)
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Add VS Code repository (RHEL-based)
      ansible.builtin.yum_repository:
        name: vscode
        description: "Visual Studio Code"
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: yes
        gpgcheck: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        repo_gpgcheck: yes
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Install VS Code package
      ansible.builtin.package:
        name: code
        state: latest
